### ISSUE TITLE
ProtocolError

### ISSUE THREAD

**Issue by iTzArshia** [unixfox/pupflare#38] opened 2024-03-31 21:36 UTC
how should I solve this? I need to have pupflare online and in another source send request to it but after few hours I got this error
```
10|Pupflare  |   ProtocolError: Target.createTarget timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
10|Pupflare  |       at <instance_members_initializer> (/root/Pupflare/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:96:14)
10|Pupflare  |       at new Callback (/root/Pupflare/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:100:16)
10|Pupflare  |       at CallbackRegistry.create (/root/Pupflare/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)
10|Pupflare  |       at Connection._rawSend (/root/Pupflare/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:80:26)
10|Pupflare  |       at Connection.send (/root/Pupflare/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:74:21)
10|Pupflare  |       at CdpBrowser._createPageInContext (/root/Pupflare/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Browser.js:178:53)
10|Pupflare  |       at CdpBrowser._createPageInContext (/root/Pupflare/node_modules/puppeteer-extra/dist/index.cjs.js:210:51)
10|Pupflare  |       at CdpBrowserContext.newPage (/root/Pupflare/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Browser.js:308:30)
10|Pupflare  |       at CdpBrowser.newPage (/root/Pupflare/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Browser.js:175:43)
10|Pupflare  |       at /root/Pupflare/index.js:39:40
```

**Comment by unixfox** [comment] 2024-04-01 00:03
No idea, maybe you entered an URL that does work? Timeout means the browser was unable to complete the request.

Closing as it's working as intended.

**Closed by unixfox** 2024-04-01 00:03 UTC
